name: Python Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v2
        with:
          python-version: '3.11'
          auto-update-conda: true
      - run: conda env create -f environment.yml
      - run: conda activate myenv && pytest
